### ISSUE TITLE
Validate the PWM Driver

### ISSUE THREAD

**Issue by Darsh-Parikh** [Space-and-Satellite-Systems-UC-Davis/IntelliSat#26]
- Use Logic Analyzers or test against a servo motor to confirm that the PWM Driver (for Orbital Platform Rev2 in particular) works fine

Document any tests to verify functionality, including the test setup (hardware-wise), the code being tested, and the result. Mention if the test passed or failed

**Comment by FofLof** [comment]
Hardware setup: 1-1 GNG 1-2 PWM AF15
Code:
`pwm_initTimer(20000);

	while (1) {
		PWM_TIMER_ON();
		pwm_setDutyCycle(1);`
Period can be seen correctly, duty cycle seen correctly - Passed (this is the same period a servo)
PWM can be be turned off - Passed (Seperate code but it just turns PWM off after ten seconds and turns it backs on after 10 seconds)

**Comment by Darsh-Parikh** [comment]
In the future simply move the task to In-Progress
For the 2nd test, is the code stored anywhere?
In both cases, it might be good to save the code as a file in the Timers folder. Refer to https://docs.google.com/document/d/1hv3hMiiT1q_joIU-QT4tFjU30lH0IN8SvIerq2Uw3Ag/edit (assuming you were testing on the master branch itself as others might now have the right support in main.c for this)

Also I'm confident in the success of this one, but in the future, it would be good to add any images or screenshots of results. If videos, upload them on the drive and then link them.
